### ISSUE TITLE
GPL3

### ISSUE THREAD

**Issue by gotwalt** [georgemandis/konami-js#13]
Really?

**Comment by georgemandis** [comment]
Is this keeping you from using it?

**Comment by gotwalt** [comment]
Yeah, I wrote my own from scratch. GPL3 + javascript libraries are a
terrible idea, unless you only want your code to be used in free (freedom)
software, in which case it's perfect. Feels heavy-handed for a library that
performs a very simple Easter egg task.

**Comment by georgemandis** [comment]
I think the GPL3 license might be a hold-over from when I had this hosted on Google Code many, many years ago and they used to make you pick a license (as I'm remembering it...). I'd honestly completely forgotten about it until you opened the issue and I had to reread what this license actually means.

Restricting this library to free software really doesn't bother me and 99% of the people using it just drop it into their blog. For those with different licensing requirements (such as yourself) it's trivial to rewrite.

Do you have an alternate license to suggest before I close the issue?

**Comment by georgemandis** [comment]
After reading a bit more about GPL3 and looking at other open-source projects I switched it to an MIT license because it seems less insane. Good call.

**Comment by gotwalt** [comment]
Cool. Thanks!

**Comment by sukima** [comment]
There is always http://tritarget.org/wywtpl/ (joking)
