### ISSUE TITLE
Feature Request: Release a version

### ISSUE THREAD

**Issue by jasondecamp** [georgemandis/konami-js#22]
In order to use bower to handle this package (along with all of the rest of my product codebase) there must be a released version. Could you please add one with the current version?

**Comment by jasondecamp** [comment]
Also, if you could add a minified version that would be great, but not necessary for my integration.

**Comment by georgemandis** [comment]
Hi @jasondecamp,

I've been generally reluctant to modify this script for any particular package managers, but things have changed a bit and I might be willing to reconsider for Bower. Can you make a pull request demonstrating what you mean precisely? Would you simply need a package.json file as part of the repo?

I don't think I'll add a minified version though.

Also: slightly curious what your product codebase is that's using konami-js, if that's publicly viewable anywhere :)

**Comment by jasondecamp** [comment]
For basic bower usage your git repo should have a tagged release version:
http://git-scm.com/book/en/v2/Git-Basics-Tagging

This way when someone uses bower to manage inclusion of your script they can add:
"konami-js": "_insert version here_"

This is also not specific to any package manager and is good practice for anyone to be able to easily navigate through the history of this script.

My project (in it's infancy) is located here: https://useabode.com
The codebase lives in a private git repo.

**Comment by sukima** [comment]
@jasondecamp I've done this at https://github.com/sukima/konami-js.git however attempting to register gives a `EDUPLICATE Duplicate package` error. So someone else has done this.

**Comment by georgemandis** [comment]
Gotchya. There is now a release:

https://github.com/snaptortoise/konami-js/releases/tag/1.4.2

I have no idea how I arrived at that version number years ago... but there we go!

I think this closes the issue but let me know if not. Also: thanks for the suggestion :)
