### ISSUE TITLE
SyntaxError: missing ; before statement

### ISSUE THREAD

**Issue by pierre-sarrazin** [georgemandis/konami-js#25]
When I used a JS minifier and I have 2 syntax errors because line breaks are removed:
1. Line 23 after `}` and before `obj.attachEvent("on"`
2. Line 96 after `}` and before `typeof callback`

**Comment by georgemandis** [comment]
Which minifier are you using? I copy/pasted the current code into here:

http://jscompress.com/

And loaded it in a test document and I'm not seeing any errors.

Probably also worth asking: which browser?

**Comment by pierre-sarrazin** [comment]
An old JS minifier... So I have removed it.
You're right, sorry.
