### ISSUE TITLE
bower.json

### ISSUE THREAD

**Issue by Rudloff** [georgemandis/konami-js#28]
It would be nice to have a [bower.json](https://github.com/bower/spec/blob/master/json.md) file for this library.

**Comment by georgemandis** [comment]
I agree. Originally I was sort of against integrating package mangers and the like, but Bower has definitely proven its staying power and I'm changing my mind.

**Comment by georgemandis** [comment]
I forgot someone had already gone ahead and set that up for me a while back! You could've been using "bower install konami-js" this whole time as it turns out, but I've added the bower.json file to the repo now as well as instructions on the examples page.

Thanks.
