### ISSUE TITLE
Touch input is not properly validated

### ISSUE THREAD

**Issue by BenBergman** [georgemandis/konami-js#30]
With the current code setup the user is able to have any gestures or taps present between the expected pattern elements and it will still execute correctly. For example, the following sequence will trigger the easter egg:

```
UP, UP, LEFT, LEFT, LEFT, LEFT, DOWN, DOWN, LEFT, RIGHT, LEFT, RIGHT, TAP, TAP
```
This could become a problem for pages that demand a lot of user interaction. Extended use of a page is likely to cause accidental triggering of the easter egg.

**Comment by georgemandis** [comment]
Good catch! Do you a have a pull request to fix it? I could review and make one but probably won't have time for a while.

**Comment by BenBergman** [comment]
I didn't have a chance to make a PR yet, but hopefully I'll have some time later this week.

**Comment by BenBergman** [comment]
I submitted a PR for this fix. Let me know if there is anything I should be doing to improve the PR.

**Comment by georgemandis** [comment]
Thanks! It seems fine, but I want to review it properly before merging in
case I thought thoughts or suggestions. I just haven't had time, but should
this weekend.
