### ISSUE TITLE
Touch input broken

### ISSUE THREAD

**Issue by tfiers** [georgemandis/konami-js#38]
#34 broke touch input by deleting and not re-introducing the code that memorises past touch inputs and that checks whether it was the Konami sequence (https://github.com/snaptortoise/konami-js/pull/34/files#diff-c82c3f68a171889fa7fc775455959b3aL78)

**Comment by georgemandis** [comment]
Shoot. Thanks for bringing that to my attention. I'll look into it.

**Comment by georgemandis** [comment]
Latest version should fix this.
