### ISSUE TITLE
Modernize code with ES6-features and functional aesthetic

### ISSUE THREAD

**Issue by georgemandis** [georgemandis/konami-js#47]
The code could stand to make better use of ES6 features and modern JavaScript coding styles. This might be the most wide-open issue in terms of solving and I'm open to all manners and discussion on the subject.

Some low hanging fruit and ideas to get started:

- Remove all instances of `var`
- Remove the custom event-listening code that existed for IE6(!!) compatibility
- Perhaps this could/should be rewritten as an [ES6 Class](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes)?
- The one `for` loop could probably be rewritten to use `forEach`

If we can get a base rewrite that adheres to this we can break down the code and discuss more specific improvements.

**Comment by DavideCarvalho** [comment]
- Removing var is quite straightforward, this shouldn't be a problem (removed on #52)
- IE6 listeners is that "attachEvent" stuff?
- I don't see why not. The only problem is this iphone property, that has a bunch of code into it.

**Comment by georgemandis** [comment]
If you take a look at the 2.0 branch I've taken a pass at a complete rewrite. Will probably be easier to discuss specific changes from there.

Going to close this issue an an effort to consolidate things.
