### ISSUE TITLE
Incorporate some kind of bundler support

### ISSUE THREAD

**Issue by georgemandis** [georgemandis/konami-js#48]
I'm not sure what approach to take here. Konami-JS has no external dependencies (which I'd like to stay that way) but I want the project to accommodate more modern toolchains. 

Should I provide separate configuration files for the more popular ones? Webpack? Parcel? Rollup?

I'm open to a big discussion here because I'm not really sure what makes the most sense for a project like this where one of my goals is to keep the barrier-to-entry low.

**Comment by DavideCarvalho** [comment]
Rollup is great for libraries. Configuration is really easy and exports for the newest js modules, like esm (es modules), so evergreen browsers can import with ```type=module```

**Comment by DavideCarvalho** [comment]
Bundlers are also great for smart bundling, [this article is great for explaining it](https://www.smashingmagazine.com/2018/10/smart-bundling-legacy-code-browsers/)
