### ISSUE TITLE
New feature discussion

### ISSUE THREAD

**Issue by georgemandis** [georgemandis/konami-js#49]
Adding new features to 2.0 was brought up (#44) when discussing a general roadmap. I'm open to suggestions! 

Currently the project listens for and triggers "easter eggs" in response to keyboard or touchscreen input. An "easter egg" can be any bit of JavaScript code but defaults to loading a new webpage in the browser.

Are there "features" that would make sense to add beyond this?

**Comment by DavideCarvalho** [comment]
I guess the feature of url redirecting isn't needed. If someone wants to redirect, create a function, put it on Konami and that's it.

**Comment by DavideCarvalho** [comment]
On konami code page, there is a "Coming soon" that has one feature

- How to track the Konami Code using Google Analytics
