### ISSUE TITLE
Create better examples and tutorials

### ISSUE THREAD

**Issue by georgemandis** [georgemandis/konami-js#50]
When version 2.0 (#44) comes out the "Getting Started" instructions for Konami-JS will have to change. I like that the new version will integrate better with modern toolchains and processes, but  I don't want to lose the ability for anyone to copy-and-paste a couple lines of code to stick it on their blog.

I'd like new examples to link to CDN-hosted versions of Konami-JS at unpkg.com. The the code will need to be written so that a distribution-ready version of `konami.js` is accessible via npm. That touches on the discussion of build-tools and bundlers (#48) to some degree.

Here are some example ideas listed under "Coming Soon!"  on the current GitHub-hosted site:

- How to present different easter eggs for gesture versus keyboard input
- How to override the default code for both keyboard and gesture
- More complex examples beyond a simple redirect
- How to track the Konami Code using Google Analytics

**Comment by DavideCarvalho** [comment]
Since Konami it's a small library, I don't think a documentation with Docusaurus or any other tool like this is necessary. Maybe a Wiki should do the trick.

**Comment by georgemandis** [comment]
Agreed. A Wiki would do fine, but seeing as lot of beginning developers end up finding and playing with the library I'd like to make more thorough demos for the GitHub page. Copy-and-paste examples for common uses cases and questions I've received over the years. Things like:

- How do I make Konami-JS load a different web page?
- How do I change the keyboard/gesture sequence?
- How do I track Konami-JS "triggers" with Google Analytics?
- How do I make a video or sound play?

That's all beyond the realm of basic API documentation, but I like the idea of providing these sort of examples, especially for newcomers.
