### ISSUE TITLE
Doc website is having an issue

### ISSUE THREAD

**Issue by DamChtlv** [georgemandis/konami-js#63]
**Describe the bug**
The doc website has infinite redirections. Impossible to access it.

**To Reproduce**
1. Go to https://konamijs.mand.is/
2. Check the console

**Expected behavior**
It would be nice to have atleast some documentations in the README if the site is not accessible.
There is no info on how to use this library at the moment.

**Screenshots**
![image](https://github.com/user-attachments/assets/bb8bc9c7-630e-42e7-aaf2-2339c22b55ae)
![image](https://github.com/user-attachments/assets/8c74eb43-39e5-4fb4-9bd4-2514e29e5e01)

**Comment by georgemandis** [comment]
Thanks @DamChtlv! Didn't realize I broke that.
 
It should be working now.
